Repository ZenBit-Tech/ZenBitRock_fe, pull requests merged in 2024-01, with the labels that each got.

#99 fix: fixed styles of go-back-button
  src/app/[locale]/verify-email/components/verify-view/verify-view.tsx
Labels: bug

#100 Fix/messages page style fixing
  src/sections/create-lead-view/form.tsx
  src/sections/messages-view/add-group-chat-button.tsx
  src/sections/messages-view/chats-list.tsx
  src/sections/messages-view/index.tsx
Labels: enhancement

#101 fix: vh to dvh for viewonmap
  src/components/custom/property/components/ViewOnMap.tsx
Labels: bug

#102 fix: remove nowrap & decresed paddingx lead history
  src/sections/lead/components/lead-history.tsx
Labels: bug

#103 Fix/update main page UI in one column
  src/components/custom/navbar/navbar.tsx
  src/components/custom/propertiesList/index.tsx
  src/components/custom/property/components/SlickSlider.tsx
  src/components/custom/property/styles.ts
  src/components/custom/propery-card/property-card.tsx
  src/components/custom/propery-card/styles.ts
  src/store/api/qobrixApi.ts
  src/types/qobrix/property/qobrix-property.type.ts
Labels: enhancement

#105 Feat/add group chat
  package-lock.json
  package.json
  src/enums/api-route.enum.ts
  src/locales/langs/en.json
  src/sections/chat/components/create-group-chat/create-group-chat.tsx
  src/sections/chat/components/create-group-chat/formFirst.tsx
  src/sections/chat/components/create-group-chat/formSecond.tsx
  src/sections/messages-view/add-group-chat-button.tsx
  src/sections/messages-view/chats-list.tsx
  src/store/chat/chat-api.ts
  src/store/chat/index.ts
  src/store/index.ts
  src/store/message/index.ts
  src/store/message/message-api.ts
  src/types/chat.ts
  src/types/index.ts
  yarn.lock
Labels: enhancement

#109 aw-21: add filter save on page close
  src/app/[locale]/main-page/lib/components/filter-list/filter-list.tsx
  src/app/[locale]/main-page/lib/components/filter-list/lib/validation-schema.ts
  src/app/[locale]/main-page/lib/components/property-filter/property-filter.tsx
  src/app/[locale]/main-page/page.tsx
  src/components/custom/index.ts
  src/components/custom/no-data-found/no-data-found.tsx
  src/components/custom/propertiesList/index.tsx
  src/enums/storage-key.enum.ts
  src/hooks/index.ts
  src/hooks/use-local-storage.ts
  src/locales/langs/en.json
  src/sections/chat/chat-nav.tsx
  src/types/main-page/property-filter-form-data.type.ts
  src/utils/property-filters/getMainPagePropertyFilter.ts
Labels: enhancement

#111 fix: + null checks
  src/app/[locale]/main-page/page.tsx
Labels: bug

#108 Added rendering data by condition on property card
  src/components/custom/property/index.tsx
  src/components/custom/propery-card/property-card.tsx
  src/components/custom/propery-card/styles.ts
  src/locales/langs/en.json
Labels: bug

#106 fix: add bug fixes and style enhancements
  src/app/[locale]/leads/lib/components/common/common.tsx
  src/app/[locale]/leads/lib/components/leads-filter/leads-filter.tsx
  src/app/[locale]/page.tsx
  src/components/custom/leadsList/index.tsx
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/constants/randomValues.ts
  src/locales/langs/en.json
  src/sections/chat/agent-network-notifications.tsx
  src/sections/chat/chat-agent-item.tsx
  src/sections/chat/chat-nav-search-results.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/chat/view/chat-view.tsx
  src/sections/user/user-del-dialog.tsx
Labels: bug, enhancement

#104 feat: added price filter
  src/app/[locale]/main-page/lib/components/filter-list/filter-list.tsx
  src/app/[locale]/main-page/lib/components/filter-list/lib/index.ts
  src/app/[locale]/main-page/lib/components/filter-list/lib/local-storage-helper.ts
  src/app/[locale]/main-page/lib/components/filter-list/lib/validation-schema.ts
  src/app/[locale]/main-page/page.tsx
  src/locales/langs/en.json
  src/types/main-page/property-filter-form-data.type.ts
  src/types/qobrix/qobrix-lead.type.ts
  src/utils/property-filters/getMainPagePropertyFilter.ts
  src/utils/property-filters/getRentalPriceFilter.ts
  yarn.lock
Labels: enhancement

#113 aw-24: update lead details UI
  src/sections/lead/components/lead-details-features-section.tsx
  src/sections/lead/components/lead-details-info-block.tsx
Labels: enhancement

#114 chore: add style corrections
  src/app/[locale]/leads/lib/components/leads-filter/leads-filter.tsx
  src/components/custom/leadsList/index.tsx
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/locales/langs/en.json
  src/sections/chat/chat-message-input.tsx
  src/sections/chat/chat-nav-search-results.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/chat/view/chat-view.tsx
Labels: bug, enhancement

#123 aw-28: property list loading
  src/components/custom/propertiesList/index.tsx
Labels: enhancement

#117 aw-25: add group chat
  src/app/[locale]/chat/live/[id]/page.tsx
  src/components/custom/chat-message-item/chat-message-item.tsx
  src/enums/chat-event.enum.ts
  src/enums/index.ts
  src/locales/langs/en.json
  src/sections/chat/live/chat-message-input.tsx
  src/sections/chat/live/chat-message-list.tsx
  src/sections/chat/live/chat-view.tsx
  src/sections/chat/live/index.ts
  src/sections/chat/live/use-messages-scroll.ts
  src/store/chat/chat-api.ts
  src/store/chat/index.ts
  src/types/chats/index.ts
  src/types/chats/message.ts
  src/types/index.ts
Labels: enhancement

#120 aw-24: lead details page scroll
  src/components/custom/app/app.tsx
  src/sections/lead/lead-details-view.tsx
  src/sections/lead/matching-properties-view.tsx
  src/store/lead/lead-api.ts
  src/types/qobrix/qobrix-pagination.type.ts
Labels: bug

#121 aw-26: matching properites
  src/enums/qobrix/qobrix-filter-keys-sale-rent.enum.ts
  src/types/qobrix/qobrix-lead.type.ts
  src/utils/property-filters/getLocationsFilter.ts
  src/utils/property-filters/getPropertySearchFilter.ts
Labels: bug

#122 aw-27: incorrect filter position
  src/app/[locale]/main-page/lib/components/filter-list/filter-list.tsx
Labels: bug

#110 Change icon-messages in header to default
  src/app/[locale]/leads/lib/components/leads-filter/leads-filter.tsx
  src/app/[locale]/main-page/lib/components/notification-center/notification-center.tsx
  src/app/[locale]/main-page/page.tsx
  src/components/custom/header/header.tsx
  src/components/custom/leadsList/components/lead-item/lead-item.tsx
  src/components/custom/leadsList/index.tsx
  src/components/custom/messages-indicator/messages-indicator.tsx
  src/enums/chat-event.enum.ts
  src/locales/langs/en.json
  src/store/api/qobrixApi.ts
  src/store/chat/chat-api.ts
  src/store/chat/index.ts
  src/store/message/message-api.ts
  src/types/message/unread-messages-quantity.type.ts
Labels: enhancement

#119 fix: fixed autocomplete bug
  src/sections/verification-view/form.tsx
Labels: bug

#125 aw-28: change main page filter placeholder
  src/app/[locale]/leads/lib/components/leads-filter/leads-filter.tsx
  src/app/[locale]/main-page/lib/components/property-filter/property-filter.tsx
  src/sections/chat/chat-nav.tsx
Labels: enhancement

#116 Feat/add chat info page
  src/app/[locale]/chat/[id]/info/page.tsx
  src/app/[locale]/leads/lib/components/leads-filter/leads-filter.tsx
  src/components/custom/leadsList/index.tsx
  src/components/custom/propertiesList/index.tsx
  src/components/custom/property/index.tsx
  src/constants/patterns.ts
  src/enums/api-route.enum.ts
  src/locales/langs/en.json
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/components/chat-info/form-add-agents.tsx
  src/sections/chat/components/chat-info/form-delete.tsx
  src/sections/chat/components/chat-info/form-name.tsx
  src/sections/chat/components/chat-info/index.ts
  src/sections/chat/components/create-group-chat/create-group-chat.tsx
  src/sections/chat/components/create-group-chat/form-add-group-chat.tsx
  src/store/chat/chat-api.ts
  src/store/chat/index.ts
  src/types/chat.ts
  src/types/index.ts
Labels: enhancement

#118 Fix/create lead page bugs
  src/constants/index.ts
  src/constants/property-price-ranges.ts
  src/locales/langs/en.json
  src/sections/create-lead-view/create-lead-view.tsx
  src/sections/create-lead-view/drop-box-data.ts
  src/sections/create-lead-view/form.tsx
  src/sections/create-lead-view/schema.ts
  src/sections/verification-view/index.tsx
  src/types/create-lead-data.ts
  src/types/qobrix/qobrix-create-lead.ts
Labels: bug

#126 aw-29: reusable no data found component
  src/components/custom/propertiesList/index.tsx
  src/locales/langs/en.json
  src/sections/chat/chat-nav-search-results.tsx
  src/sections/messages-view/chats-list.tsx
Labels: enhancement

#124 feat: add private chat connection, fix components for real chat data
  package-lock.json
  package.json
  src/app/[locale]/chat/[id]/page.tsx
  src/app/[locale]/chats/[id]/page.tsx
  src/app/[locale]/messages/[id]/page.tsx
  src/app/[locale]/messages/layout.tsx
  src/app/[locale]/messages/page.tsx
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/constants/dates-formats.ts
  src/enums/api-route.enum.ts
  src/enums/app-route.enum.ts
  src/enums/chat-event-enum.ts
  src/enums/index.ts
  src/locales/langs/en.json
  src/sections/chat/chat-header-detail.tsx
  src/sections/chat/chat-message-input.tsx
  src/sections/chat/chat-message-list.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/hooks/use-messages-scroll.ts
  src/sections/chat/utils/generateMockMsgs.ts
  src/sections/chat/view/chat-view.tsx
  src/store/chat/chat-api.ts
  src/store/chat/index.ts
  src/types/chat.ts
  src/utils/format-time.ts
  yarn.lock
Labels: enhancement

#127 Feat/create lead page go back button
  src/app/[locale]/chats/[id]/info/page.tsx
  src/app/[locale]/chats/[id]/page.tsx
  src/app/[locale]/chats/layout.tsx
  src/app/[locale]/chats/live/[id]/page.tsx
  src/app/[locale]/chats/page.tsx
  src/components/custom/go-back-page-title/go-back-page-title.tsx
  src/components/custom/messages-indicator/messages-indicator.tsx
  src/components/custom/property/index.tsx
  src/enums/app-route.enum.ts
  src/locales/langs/en.json
  src/sections/change-password-view/form.tsx
  src/sections/chat/agent-network-notifications.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/components/chat-info/form-delete.tsx
  src/sections/chat/components/create-group-chat/create-group-chat.tsx
  src/sections/chats-view/add-group-chat-button.tsx
  src/sections/chats-view/chat-item.tsx
  src/sections/chats-view/chats-list.tsx
  src/sections/chats-view/drop-box-data.ts
  src/sections/chats-view/index.tsx
  src/sections/chats-view/sort-component.tsx
  src/sections/create-lead-view/create-lead-view.tsx
  src/sections/create-lead-view/form.tsx
  src/sections/restore-password-done-view/index.tsx
  src/sections/restore-password-view/form.tsx
  src/sections/verify-code-view/form.tsx
  yarn.lock
Labels: enhancement

#128 Fix/put leads search filter values to localstorage
  src/app/[locale]/leads/lib/components/leads-filter/leads-filter.tsx
  src/components/custom/header/lib/header-avatar.tsx
  src/components/custom/leadsList/index.tsx
  src/components/custom/messages-indicator/messages-indicator.tsx
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/components/chat-info/form-name.tsx
  src/sections/chat/components/create-group-chat/form-add-group-chat.tsx
Labels: bug

#129 chore(leads-filter): correct status name, add default status
  src/app/[locale]/leads/lib/components/leads-filter/leads-filter.tsx
  src/components/custom/leadsList/index.tsx
  src/constants/leadStatuses.ts
  src/locales/langs/en.json
Labels: enhancement

#134 Fix/change some styles
  src/app/[locale]/main-page/lib/components/notification-center/notification-center.tsx
  src/app/[locale]/main-page/lib/components/property-filter/property-filter.tsx
  src/app/[locale]/main-page/page.tsx
  src/components/custom/leadsList/styles.ts
  src/components/custom/propertiesList/index.tsx
  src/components/custom/property/components/InfoBlock.tsx
  src/components/custom/property/components/SlickSlider.tsx
  src/components/custom/property/styles.ts
  src/components/custom/propery-card/property-card.tsx
  src/components/custom/propery-card/styles.ts
  src/locales/langs/en.json
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/components/chat-info/form-add-agents.tsx
  src/sections/chat/components/chat-info/form-delete.tsx
  src/sections/chat/components/chat-info/form-name.tsx
  src/sections/chat/components/create-group-chat/form-add-group-chat.tsx
  src/sections/lead/components/lead-history.tsx
Labels: enhancement

#133 fix: corrected design
  src/hooks/use-scroll-to-top.ts
  src/sections/agent-network-view/index.tsx
  src/sections/chat/agent-network-notifications.tsx
  src/sections/chat/agent-sort.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/user/profile-cover.tsx
  yarn.lock
Labels: enhancement

#135 Feat/add content page front & connect
  src/app/[locale]/content/page.tsx
  src/components/custom/content-view/components/article-item.tsx
  src/components/custom/content-view/components/article-list.tsx
  src/components/custom/content-view/components/content-filter.tsx
  src/components/custom/content-view/components/content-sort.tsx
  src/components/custom/content-view/components/index.ts
  src/components/custom/content-view/components/video-item.tsx
  src/components/custom/content-view/components/video-list.tsx
  src/components/custom/content-view/index.tsx
  src/components/custom/content-view/utils/sortContent.ts
  src/components/custom/navbar/lib/useNavItems.hook.tsx
  src/constants/colors.ts
  src/constants/contentSortOptions.ts
  src/enums/api-route.enum.ts
  src/enums/app-route.enum.ts
  src/locales/langs/en.json
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/components/chat-info/form-add-agents.tsx
  src/store/content/content-api.ts
  src/store/content/index.ts
  src/store/index.ts
  src/types/content.ts
  src/types/index.ts
Labels: enhancement

#138 Fix/logo and lead validation
  src/components/custom/header/styles.ts
  src/locales/langs/en.json
  src/sections/create-lead-view/form.tsx
  src/types/qobrix/qobrix-create-lead.ts
Labels: enhancement

#131 aw-31: fix socket data fetching
  src/store/chat/chat-api.ts
Labels: bug

#139 aw-30: filter resize and small screen
  src/app/[locale]/main-page/lib/components/property-filter/property-filter.tsx
  src/components/custom/no-data-found/no-data-found.tsx
Labels: enhancement

#140 aw-32: delete yarn lock for heroku deploy
  yarn.lock
Labels: enhancement

#143 aw-33: one page for group and private chat
  public/manifest.json
  src/app/[locale]/chats/[id]/page.tsx
  src/app/[locale]/chats/live/[id]/page.tsx
  src/sections/chat/agent-network-notifications.tsx
  src/sections/chat/chat-group-header.tsx
  src/sections/chat/chat-message-list.tsx
  src/sections/chat/view/chat-view.tsx
  src/store/chat/chat-api.ts
  src/types/chat.ts
  src/types/chats/chat-info-response.type.ts
  src/types/chats/index.ts
Labels: enhancement

#142 Fix/style bugs
  src/app/[locale]/content/page.tsx
  src/components/custom/content-view/index.tsx
  src/components/custom/header/header.tsx
  src/components/custom/leadsList/components/lead-item/lead-item.tsx
  src/constants/patterns.ts
  src/locales/langs/en.json
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/components/chat-info/form-add-agents.tsx
  src/sections/chat/components/chat-info/form-delete.tsx
  src/sections/lead/components/history-hooks/use-all-pages-data-calls.ts
  src/sections/lead/components/history-hooks/use-all-pages-data-emails.ts
  src/sections/lead/components/history-hooks/use-all-pages-data-meetings.ts
  src/sections/lead/components/history-hooks/use-all-pages-data-smses.ts
  src/sections/lead/components/history-hooks/use-all-pages-data-status-changes.ts
  src/sections/lead/components/history-hooks/use-all-pages-data-task-changes.ts
  src/sections/lead/components/history-hooks/use-all-pages-data-tasks.ts
  src/sections/lead/components/lead-history.tsx
Labels: bug, enhancement

#145 Fix/remove loader under header
  src/app/[locale]/chats/[id]/page.tsx
  src/app/[locale]/leads/[id]/page.tsx
  src/app/[locale]/sign-in/page.tsx
  src/app/[locale]/sign-up/page.tsx
  src/sections/agent-network-view/index.tsx
  src/sections/chat/chat-header-detail.tsx
  src/sections/chat/chat-message-input.tsx
  src/sections/chat/live/chat-message-input.tsx
  src/sections/create-lead-view/create-lead-view.tsx
Labels: bug

#146 fix: added owner to chat members
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/components/chat-info/form-add-agents.tsx
  src/sections/chat/components/create-group-chat/form-add-group-chat.tsx
Labels: bug

#147 feat(ui): display deleted user accounts and improve private chat display
  src/app/[locale]/chats/[id]/page.tsx
  src/constants/errMessages.ts
  src/locales/langs/en.json
  src/sections/chat/chat-agent-item.tsx
  src/sections/chat/chat-header-detail.tsx
  src/sections/chat/view/chat-view.tsx
  src/store/auth/authApi.ts
  src/types/user-backend/user-chat-reponse.type.ts
  src/types/user-backend/user-profile-response.type.ts
Labels: enhancement

#150 Fix/style bugs second
  src/components/custom/header/header.tsx
  src/enums/app-route.enum.ts
  src/locales/langs/en.json
Labels: bug

#148 Feat/onboarding tutorial
  .env.example
  package-lock.json
  package.json
  src/app/[locale]/chats/[id]/page.tsx
  src/app/[locale]/layout.tsx
  src/app/[locale]/leads/lib/components/common/common.tsx
  src/app/[locale]/main-page/lib/components/notification-center/notification-center.tsx
  src/app/[locale]/main-page/page.tsx
  src/components/custom/content-view/index.tsx
  src/components/custom/header/header.tsx
  src/components/custom/index.ts
  src/components/custom/leadsList/components/lead-item/lead-item.tsx
  src/components/custom/leadsList/index.tsx
  src/components/custom/messages-indicator/messages-indicator.tsx
  src/components/custom/onboarding/context.tsx
  src/components/custom/onboarding/index.ts
  src/components/custom/onboarding/onboarding-mock-data.ts
  src/components/custom/onboarding/onboarding-steps.tsx
  src/components/custom/onboarding/onboarding.tsx
  src/components/custom/propertiesList/index.tsx
  src/components/custom/propery-card/property-card.tsx
  src/components/nav-section/horizontal/nav-section-horizontal.tsx
  src/constants/property-price-ranges.ts
  src/hooks/index.ts
  src/locales/langs/en.json
  src/sections/agent-network-view/index.tsx
  src/sections/chat/chat-agent-item.tsx
  src/sections/chat/chat-header-detail.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/chats-view/add-group-chat-button.tsx
  src/sections/chats-view/chat-item.tsx
  src/sections/chats-view/chats-list.tsx
  src/sections/chats-view/index.tsx
  src/sections/create-lead-view/schema.ts
  src/sections/lead/lead-details-view.tsx
  src/sections/lead/matching-properties-view.tsx
  src/sections/quick-start-guide-view/quick-start-guide-view.tsx
  src/sections/verify-old-password-view/index.tsx
Labels: enhancement

#152 aw-35: group chat messages and error page
  src/app/[locale]/chats/[id]/page.tsx
  src/locales/langs/en.json
  src/sections/chat/chat-message-list.tsx
  src/sections/chat/view/chat-view.tsx
  src/sections/compact/layout.tsx
  src/sections/error/index.ts
  src/sections/error/not-a-chat-member-view.tsx
  src/sections/index.ts
Labels: enhancement

#151 fix: added condition owner or not
  src/sections/chat/components/chat-info/chat-info.tsx
  src/types/chat.ts
  src/types/chats/chat-info-response.type.ts
Labels: bug

#153 feat: add looking for to lead
  src/components/custom/leadsList/components/lead-item/lead-item.tsx
  src/components/custom/leadsList/index.tsx
  src/locales/langs/en.json
  src/store/api/qobrixApi.ts
  src/types/qobrix/qobrix-lead-list.type.ts
Labels: enhancement

#154 feat: connect receive notifications status update functionality
  src/app/[locale]/main-page/lib/components/notification-center/notification-center.tsx
  src/enums/api-route.enum.ts
  src/sections/user/user-edit-settings.tsx
  src/store/api/userApi.ts
  src/types/user-backend/user-profile-response.type.ts
  src/types/user.ts
Labels: enhancement

#155 Feat/messages page connect
  src/components/custom/chat-message-item/chat-message-item.tsx
  src/components/custom/leadsList/index.tsx
  src/components/custom/onboarding/onboarding-mock-data.ts
  src/components/custom/onboarding/onboarding-steps.tsx
  src/constants/colors.ts
  src/enums/app-route.enum.ts
  src/enums/chat-event.enum.ts
  src/enums/index.ts
  src/sections/chats-view/chat-item.tsx
  src/sections/chats-view/chats-list.tsx
  src/sections/chats-view/helpers/drop-box-data.ts
  src/sections/chats-view/helpers/get-opponent-avatar.ts
  src/sections/chats-view/helpers/get-opponent.ts
  src/sections/chats-view/helpers/index.ts
  src/sections/chats-view/helpers/messages-helper.ts
  src/sections/chats-view/helpers/sort-chats.ts
  src/sections/chats-view/index.tsx
  src/sections/chats-view/sort-component.tsx
  src/sections/lead/lead-details-view.tsx
  src/services/trim-string-helper.ts
  src/store/chat/chat-api.ts
  src/types/chats/chat.ts
  src/types/chats/index.ts
  src/types/index.ts
  src/types/user-data.ts
Labels: enhancement

#157 aw-36: update lead details UI
  src/sections/lead/components/lead-delete-component.tsx
  src/sections/lead/components/lead-details-budget-section.tsx
  src/sections/lead/components/lead-details-features-section.tsx
  src/sections/lead/components/lead-details-info-block.tsx
  src/sections/lead/components/lead-details-source-section.tsx
  src/sections/lead/lead-details-view.tsx
  src/sections/lead/matching-properties-view.tsx
Labels: enhancement

#156 Fix/add owner to lead
  src/components/custom/onboarding/onboarding-mock-data.ts
  src/enums/api-route.enum.ts
  src/sections/create-lead-view/form.tsx
  src/sections/verification-view/form.tsx
  src/store/api/qobrixApi.ts
  src/types/index.ts
  src/types/qobrix/index.ts
  src/types/qobrix/qobrix-add-user-to-group.ts
  src/types/qobrix/qobrix-create-lead.ts
  src/types/qobrix/qobrix-user.ts
  src/types/user-backend/user-profile-response.type.ts
  src/types/user.ts
Labels: enhancement

#158 fix: corrected contact made status display
  src/components/custom/leadsList/components/lead-item/lead-item.tsx
  src/constants/leadStatuses.ts
  src/constants/randomValues.ts
  src/locales/langs/en.json
Labels: enhancement

#160 Feat/content connect
  src/app/[locale]/global.css
  src/components/custom/content-view/components/article-item.tsx
  src/components/custom/content-view/components/article-list.tsx
  src/components/custom/content-view/components/video-item.tsx
  src/components/custom/content-view/components/video-list.tsx
  src/components/custom/content-view/index.tsx
  src/components/custom/property/index.tsx
  src/enums/api-route.enum.ts
  src/store/content/content-api.ts
Labels: enhancement

#159 feat: corrected deleted user chat info display
  src/app/[locale]/main-page/lib/components/notification-center/notification-center.tsx
  src/components/custom/chat-message-item/chat-message-item.tsx
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/components/custom/onboarding/onboarding-mock-data.ts
  src/locales/langs/en.json
  src/sections/chat/chat-agent-item.tsx
  src/types/user-data.ts
Labels: enhancement

#162 fix: changed group id
  src/sections/verification-view/form.tsx
  src/store/api/qobrixApi.ts
  src/types/index.ts
  src/types/qobrix/index.ts
  src/types/qobrix/qobrix-add-user-to-group.ts
  src/types/qobrix/qobrix-groups.ts
Labels: bug

#164 Fix: undo content loading & chat members owner
  src/components/custom/content-view/components/article-item.tsx
  src/components/custom/content-view/components/content-item.tsx
  src/components/custom/content-view/components/content-list.tsx
  src/components/custom/content-view/components/index.ts
  src/components/custom/content-view/components/video-list.tsx
  src/components/custom/content-view/index.tsx
  src/locales/langs/en.json
  src/sections/chat/components/chat-info/chat-info.tsx
Labels: bug

#166 fix: msg time display
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
Labels: bug

#167 aw-38: keep socket connection
  src/app/[locale]/tutorial-page/page.tsx
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/store/chat/chat-api.ts
Labels: enhancement

#169 fix: add filter on option
  src/sections/chat/components/chat-info/form-add-agents.tsx
Labels: bug

#163 feat: connect agents network to synchronized users endpoint
  src/enums/api-route.enum.ts
  src/sections/agent-network-view/index.tsx
  src/store/api/userApi.ts
Labels: enhancement

#161 Feat/unread messages connect
  src/app/[locale]/chats/[id]/page.tsx
  src/components/custom/chat-message-item/chat-message-item.tsx
  src/components/custom/content-view/utils/getIsRead.ts
  src/components/custom/messages-indicator/messages-indicator.tsx
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/components/custom/onboarding/onboarding-mock-data.ts
  src/enums/chat-event-enum.ts
  src/enums/chat-event.enum.ts
  src/sections/chat/components/chat-info/form-add-agents.tsx
  src/sections/chats-view/chat-item.tsx
  src/sections/chats-view/helpers/index.ts
  src/sections/chats-view/helpers/messages-helper.ts
  src/store/chat/chat-api.ts
  src/store/chat/index.ts
  src/types/chats/message.ts
Labels: bug, enhancement

#172 Fix/chats and guide
  src/locales/langs/en.json
  src/sections/agent-network-view/index.tsx
  src/sections/chats-view/chat-item.tsx
  src/sections/chats-view/chats-list.tsx
  src/store/chat/chat-api.ts
Labels: enhancement

#173 Fix/query leads by property
  src/app/[locale]/leads/lib/components/common/common.tsx
  src/components/custom/leadsList/index.tsx
  src/components/custom/property/helpers/searchParams.ts
  src/components/custom/property/helpers/searchString.ts
  src/components/custom/property/index.tsx
  src/components/custom/propery-card/property-card.tsx
  src/components/nav-section/horizontal/nav-item.tsx
  src/store/api/qobrixApi.ts
  src/types/qobrix/property/qobrix-property-detailed.type.ts
Labels: bug

#174 fix: added unread messages on agents
  src/sections/chat/chat-agent-item.tsx
  src/sections/chat/chat-nav.tsx
  src/store/chat/chat-api.ts
Labels: bug

#175 Fix/verification done page
  src/app/[locale]/verification/layout.tsx
  src/app/[locale]/verification/page.tsx
  src/components/custom/onboarding/onboarding-mock-data.ts
  src/hooks/use-verification.hook.ts
  src/locales/langs/en.json
  src/sections/verification-done-view/index.tsx
  src/sections/verification-view/form.tsx
  src/sections/verification-view/index.tsx
  src/types/user-backend/user-profile-response.type.ts
  src/types/user.ts
Labels: bug

#176 fix: change condition on agents list
  src/components/custom/property/helpers/searchParams.ts
  src/components/nav-section/horizontal/nav-item.tsx
  src/sections/chat/chat-agent-item.tsx
  src/sections/chat/chat-nav.tsx
Labels: enhancement

#170 feat(properties): add applied filters display
  src/app/[locale]/main-page/lib/components/filter-list/filter-list.tsx
  src/app/[locale]/main-page/lib/components/property-filter/property-filter.tsx
  src/app/[locale]/main-page/page.tsx
  src/constants/randomValues.ts
  src/enums/storage-key.enum.ts
  src/sections/user/profile-cover.tsx
  src/types/main-page/property-filter-form-data.type.ts
  src/utils/property-filters/getFilterString.ts
  src/utils/property-filters/index.ts
Labels: enhancement

#171 fix: add corrections to group chats display
  src/sections/chat/chat-group-header.tsx
  src/sections/chat/view/chat-view.tsx
  src/sections/chats-view/index.tsx
Labels: enhancement

#177 Feat/add unread messages tick in group chats
  src/components/custom/chat-message-item/chat-message-item.tsx
  src/components/custom/chat-message-item/utils/getIsRead.ts
  src/components/custom/chat-message-item/utils/getIsReadByMembers.ts
  src/components/custom/chat-message-item/utils/getReaders.ts
  src/components/custom/chat-message-item/utils/index.ts
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/locales/langs/en.json
  src/sections/chat/chat-message-list.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/components/chat-info/form-add-agents.tsx
  src/sections/chat/components/chat-info/form-delete.tsx
  src/sections/chat/live/chat-message-list.tsx
  src/sections/chat/live/chat-view.tsx
  src/sections/chat/view/chat-view.tsx
Labels: enhancement

#179 aw-37: notifications
  src/app/[locale]/main-page/lib/components/filter-list/filter-list.tsx
  src/app/[locale]/main-page/lib/components/property-filter/property-filter.tsx
  src/app/[locale]/notifications/page.tsx
  src/components/custom/index.ts
  src/components/custom/page-title/page-title.tsx
  src/components/custom/property/helpers/searchParams.ts
  src/enums/chat-event.enum.ts
  src/layouts/index.ts
  src/layouts/mobile/mobile-layout.tsx
  src/locales/langs/en.json
  src/sections/index.ts
  src/sections/lead/lead-details-view.tsx
  src/sections/notifications/index.ts
  src/sections/notifications/user-notifications-view.tsx
  src/store/index.ts
  src/store/notification/index.ts
  src/store/notification/notification-api.ts
  src/types/index.ts
  src/types/notifications/index.ts
  src/types/notifications/notification.type.ts
  src/utils/property-filters/getFilterString.ts
Labels: enhancement

#181 aw-39: extend notification UI and api
  src/enums/chat-event.enum.ts
  src/sections/notifications/components/index.ts
  src/sections/notifications/components/notification-card.tsx
  src/sections/notifications/user-notifications-view.tsx
  src/store/app-socket-factory.ts
  src/store/chat/chat-api.ts
  src/store/notification/index.ts
  src/store/notification/notification-api.ts
  src/types/notifications/notification.type.ts
Labels: enhancement

#178 feat(crm-connect): added corrections according to the be changes
  src/constants/agentRoles.ts
  src/sections/user/profile-home.tsx
  src/sections/user/user-new-edit-form.tsx
  src/store/api/qobrixApi.ts
  src/types/user-backend/user-profile-response.type.ts
  src/types/user.ts
Labels: enhancement

#182 feat: added pwa
  next.config.js
  package-lock.json
  package.json
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/manifest.json
  src/app/[locale]/layout.tsx
Labels: enhancement

#183 Fix: prevent deleting chat owner when member leave
  src/sections/chat/components/chat-info/form-delete.tsx
Labels: bug

#186 aw-40: update notification UI and api
  src/app/[locale]/layout.tsx
  src/app/[locale]/main-page/lib/components/notification-center/notification-center.tsx
  src/constants/agentRoles.ts
  src/enums/app-route.enum.ts
  src/locales/langs/en.json
  src/sections/chat/live/chat-message-input.tsx
  src/sections/chat/live/chat-message-list.tsx
  src/sections/chat/live/chat-view.tsx
  src/sections/chat/live/index.ts
  src/sections/chat/live/use-messages-scroll.ts
  src/sections/notifications/components/notification-card.tsx
  src/sections/notifications/user-notifications-view.tsx
  src/store/notification/notification-api.ts
  src/types/notifications/notification.type.ts
Labels: enhancement

#184 Fix/hide chost users
  src/sections/chat/components/chat-info/chat-info.tsx
  src/sections/chat/components/chat-info/form-add-agents.tsx
  src/sections/chat/components/chat-info/form-delete.tsx
  src/types/user-backend/user-chat-reponse.type.ts
Labels: bug

#188 fix: changed filter string display location
  src/app/[locale]/layout.tsx
  src/app/[locale]/main-page/lib/components/property-filter/property-filter.tsx
Labels: enhancement

#189 fix: add corrections
  src/components/custom/content-view/components/add-content-form.tsx
  src/components/custom/content-view/components/content-item.tsx
  src/constants/patterns.ts
  src/locales/langs/en.json
  src/sections/agent-network-view/index.tsx
Labels: bug, enhancement
