Repository ZenBit-Tech/ZenBitRock_fe, pull requests merged in 2024-02, with the labels that each got.

#190 Fix/map button close improvement
  src/components/custom/chat-message-item/chat-message-item.tsx
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/components/custom/property/components/InfoBlock.tsx
  src/components/custom/property/components/ViewOnMap.tsx
  src/components/custom/propery-card/property-card.tsx
  src/store/api/qobrixApi.ts
  src/store/chat/chat-api.ts
  src/store/lead/lead-api.ts
  src/types/qobrix/property/qobrix-property.type.ts
Labels: bug

#193 Task/aw 41 add mark as read
  src/app/[locale]/main-page/lib/components/notification-center/notification-center.tsx
  src/enums/chat-event.enum.ts
  src/sections/notifications/components/notification-card.tsx
  src/sections/notifications/user-notifications-view.tsx
  src/store/notification/index.ts
  src/store/notification/notification-api.ts
  src/types/notifications/notification.type.ts
Labels: enhancement

#191 feat(filter): add price formatting
  src/app/[locale]/main-page/lib/components/filter-list/filter-list.tsx
  src/app/[locale]/main-page/lib/components/filter-list/lib/validation-schema.ts
  src/components/hook-form/index.ts
  src/components/hook-form/rhf-num-formatted-field.tsx
  src/constants/fieldFormats.ts
  src/utils/property-filters/getFilterString.ts
Labels: enhancement

#195 Feat/saving of search params
  .eslintrc
  src/app/[locale]/layout.tsx
  src/app/[locale]/main-page/lib/components/filter-list/filter-list.tsx
  src/app/[locale]/main-page/lib/components/filter-list/lib/index.ts
  src/app/[locale]/main-page/lib/components/property-filter/property-filter.tsx
  src/app/[locale]/main-page/page.tsx
  src/components/nav-section/horizontal/nav-section-horizontal.tsx
  src/enums/storage-key.enum.ts
  src/sections/chats-view/chats-list.tsx
  src/services/index.ts
  src/services/local-storage-helper.ts
Labels: enhancement

#196 feat: add is-user-in-crm check on registration and kyc
  src/constants/errMessages.ts
  src/sections/verification-view/form.tsx
  src/types/qobrix/qobrix-agent.ts
  src/types/qobrix/qobrix-contact.ts
Labels: enhancement

#199 fix: go-top-button
  src/sections/chats-view/chats-list.tsx
Labels: bug

#201 zw-43 : chat-and-message-doubling
  src/sections/chat/chat-agent-item.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/notifications/helpers/getNotificationIcon.helper.tsx
  src/store/chat/chat-api.ts
Labels: bug

#200 feat: add agents filter saving
  src/enums/storage-key.enum.ts
  src/sections/chat/chat-nav-search-results.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/user/profile-cover.tsx
Labels: enhancement

#202 Fix/aw 44 private chat doubling
  src/sections/agent-network-view/index.tsx
  src/sections/chat/chat-nav-search-results.tsx
  src/sections/chat/chat-nav.tsx
Labels: bug

#197 Feat/add likes to messages
  src/app/[locale]/global.css
  src/components/custom/chat-message-item/chat-message-item.tsx
  src/components/custom/chat-message-item/utils/getLike.ts
  src/components/custom/chat-message-item/utils/getLikes.ts
  src/components/custom/chat-message-item/utils/index.ts
  src/components/custom/mock-chat-message-item/like.tsx
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/components/custom/onboarding/onboarding-mock-data.ts
  src/enums/chat-event.enum.ts
  src/store/chat/chat-api.ts
  src/store/chat/index.ts
  src/types/chats/message.ts
Labels: enhancement

#204 aw-45: private chat doubling
  src/components/hook-form/rhf-num-formatted-field.tsx
  src/constants/fieldFormats.ts
  src/sections/chat/chat-agent-item.tsx
  src/sections/chat/chat-nav-search-results.tsx
  src/sections/chat/chat-nav.tsx
  src/sections/lead/lead-details-view.tsx
  src/store/chat/chat-api.ts
  src/store/chat/index.ts
Labels: bug

#206 Fix/likes & history & loader
  src/components/custom/mock-chat-message-item/mock-chat-message-item.tsx
  src/components/custom/protected-route/protected-route.tsx
  src/sections/lead/components/lead-history.tsx
  src/sections/user/profile-home.tsx
Labels: bug

#207 chore: add ui fixes
  src/app/[locale]/sign-in/components/form/index.tsx
  src/components/SignUpForm/SignUpForm.tsx
  src/components/custom/content-view/components/content-item.tsx
Labels: bug, enhancement

#205 fix: updated chat list
  src/sections/chats-view/chats-list.tsx
Labels: bug

#208 Fix/some UI bugs
  src/app/[locale]/chats/[id]/page.tsx
  src/components/custom/content-view/components/content-list.tsx
  src/components/custom/mock-chat-message-item/like.tsx
  src/enums/chat-event.enum.ts
  src/locales/langs/en.json
  src/sections/chat/components/chat-info/chat-info.tsx
  src/store/chat/chat-api.ts
  src/store/chat/index.ts
Labels: bug

#209 Fix/empty leads list
  src/components/custom/navbar/lib/useNavItems.hook.tsx
  src/components/nav-section/horizontal/nav-item.tsx
  src/components/nav-section/types.ts
  src/sections/chat/components/chat-info/form-delete.tsx
Labels: bug

#210 Fix/chats-search
  src/components/custom/onboarding/onboarding-mock-data.ts
  src/sections/chat/chat-nav.tsx
  src/sections/chats-view/chats-list.tsx
  src/sections/user/profile-home.tsx
  src/store/chat/chat-api.ts
  src/types/chats/chat.ts
  src/types/chats/index.ts
  src/types/index.ts
Labels: bug

#211 Feat: change bedrooms to min.bedrooms
  src/app/[locale]/main-page/lib/components/property-filter/property-filter.tsx
  src/locales/langs/en.json
Labels: enhancement
